import { ClerkProvider } from "@clerk/nextjs";
import { Asap } from "next/font/google";

import "../globals.css";

const font = Asap({ subsets: ["latin"] });

export const metadata = {
  title: "Parfemi | Prijava",
  description: "Generated by Next.js",
};

const localization = {
  socialButtonsBlockButton: 'Nastavite uz {{provider|titleize}}',
  dividerText: 'ili',
  formFieldLabel__emailAddress: 'Email adresa',
  formFieldLabel__username: 'Korisničko ime',
  formFieldLabel__password: 'Lozinka',
  formFieldLabel__currentPassword: 'Trenutna lozinka',
  formFieldLabel__newPassword: 'Nova lozinka',
  formFieldLabel__confirmPassword: 'Potvrdite lozinku',
  formFieldLabel__firstName: 'Ime',
  formFieldLabel__lastName: 'Prezime',
  formButtonPrimary: 'Nastavite',
  formFieldHintText__optional: 'Opcionalno',
  passwordComplexity: {
    sentencePrefix: 'Lozinka mora sadržavati',
    minimumLength: '{{length}} ili više znakova',
    maximumLength: 'manje od {{length}} znakova',
  },
  signIn: {
    start: {
      title: 'Prijava',
      subtitle: 'za nastavak na {{applicationName}}',
      actionText: 'Nemate račun?',
      actionLink: 'Registrirajte se',
    }
  },
  signUp: {
    start: {
      title: 'Napravite novi račun',
      subtitle: 'za nastavak na {{applicationName}}',
      actionText: 'Već imate račun?',
      actionLink: 'Prijava',
    },
  }
}

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider localization={localization}>
      <html lang="en">
        <body className={font.className}>
          <div className="w-full min-h-screen flex justify-center items-center">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
