import { ClerkProvider } from "@clerk/nextjs";
import { Asap } from "next/font/google";

import "../globals.css";

const font = Asap({ subsets: ["latin"] });

export const metadata = {
  title: "Parfemi | Prijava",
  description: "Generated by Next.js",
};

export default function AuthLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body className={font.className}>
          <div className="w-full min-h-screen flex justify-center items-center">
            {children}
          </div>
        </body>
      </html>
    </ClerkProvider>
  );
}
